Point2Point/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('home.urls')),
    url(r'^quests/', include('quests.urls')),
    url(r'^leaderboards/', include('leaderboards.urls')),
    url(r'^about/', include('about.urls')),
    url(r'^contact/', include('contact.urls')),
   	url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout',
     {'next_page': '/'}),
   	url(r'^accounts/', include('allauth.urls')),    
    url(r'^profile/', include('userprofile.urls')),
    url(r'^howtoplay/', include('howtoplay.urls')),  
    url(r'^payment/', include('payment.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),  
)

home/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from home import views
from quests import web_views
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
    url(r'^quests/(?P<quest_type_id>\d+)/(?P<short_name>[-\w\d]+)/$', web_views.quest_list_type, name='quest_type'),
)

userprofile/urls.py
from django.conf.urls import patterns, url, include
from userprofile import views
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.user_profile, name='userprofile'),
    url(r'^ajax/', views.ajax, name='ajax'),
    url(r'^ajax_send_pin/', views.ajax_send_pin, name='ajax send pin'),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    game_instances = models.ManyToManyField("quests.GameInstance", blank=True, null=True)
    email_alerts = models.BooleanField(default=False)
    phone_number_verified = models.BooleanField(default=False)
    def __unicode__(self):
        return self.user.username

class ProfilePhoneNumber(models.Model):
	user_profile = models.ForeignKey('UserProfile')
	phone_number = models.CharField(max_length=15)

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

userprofile/forms.py
from django import forms
from models import UserProfile, ProfilePhoneNumber
from phonenumber_field.modelfields import PhoneNumberField


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['email_alerts',]
        labels = {'email_alerts': ('I want to receive email alerts'),}


#Commented out until "This Field Cannot be null" is figured out"

class GetPinForm(forms.Form):

    phone_number = forms.RegexField(regex=r'^\+?1?\d{9,15}$', 
                                error_message = ("Phone number must include country code '+x-xxx-xxx-xxxx'."), 
                                max_length=15,
                                label=u'Phone Number')

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(GetPinForm, self).__init__(*args, **kwargs)

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if self.user:
            phone_numbers = ProfilePhoneNumber.objects.filter(user_profile=self.user.profile).filter(phone_number=phone_number)
            if phone_numbers:
                raise forms.ValidationError('You have already registered this number')
            else:
                return phone_number
        else:
            raise forms.ValidationError('Not sure how you managed this, but you aren\'t logged in. Please log in')

class VerifyPinForm(forms.Form):
    pin = forms.CharField(max_length=10)

userprofile/views.py
from Point2Point.settings import TWILIO_ACCOUNT_SID,TWILIO_AUTH_TOKEN,TWILIO_NUMBER
from django.shortcuts import render_to_response, RequestContext, HttpResponse, render
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.core.context_processors import csrf
from django.views.decorators.csrf import csrf_protect
from twilio.rest import TwilioRestClient
from forms import UserProfileForm, GetPinForm, VerifyPinForm
from django.contrib.auth.decorators import login_required
from phonenumber_field.modelfields import PhoneNumberField
from quests.models import Team, GameInstance, QuestType
from models import ProfilePhoneNumber
import phonenumbers
import string
import random
import json
from django.utils import simplejson
from django.core import serializers


@login_required
def ajax(request):

    name = request.GET['name']
    user = request.user
    profile = user.profile

    #data = serializers.serialize("json", ProfilePhoneNumber.objects.all())

    data = serializers.serialize('json', [ user, ])

    return_dict = {
        'name': name,
        'user': data
    }
    json = simplejson.dumps(return_dict)
    return HttpResponse(json, mimetype="application/x-javascript")

    #return render_to_response('userprofile/ajax.html', locals(), context_instance=RequestContext(request))

def get_phone_numbers(user_profile):
    verified_numbers = ProfilePhoneNumber.objects.filter(user_profile=user_profile)    
    verified_number_list = []
    for number in verified_numbers:
        verified_number_list.append(number.phone_number)
    return verified_number_list

@login_required
def user_profile(request):
    args = {}
    in_progress_list = []
    completed_list = []
    verified_number_list = []
    user = request.user
    profile = user.profile
    games = profile.game_instances.all()
    for game in games:
        if game.ended:
            completed_list.append(game)
        else:
            in_progress_list.append(game)
    verified_numbers = ProfilePhoneNumber.objects.filter(user_profile=profile)
    for number in verified_numbers:
        verified_number_list.append(number.phone_number)
    get_pin_form = GetPinForm(user=request.user)
    verify_pin_form = VerifyPinForm()
    quest_types = QuestType.objects.filter(front_page=True).order_by('priority')
    args['in_progress_list'] = in_progress_list
    args['completed_list'] = completed_list
    args['verified_number_list'] = verified_number_list
    args['username'] = user.username
    args['phone_number_verified'] = user.profile.phone_number_verified
    args['get_pin_form'] = get_pin_form
    args['verify_pin_form'] = verify_pin_form
    args['quest_types'] = quest_types
    return render_to_response('userprofile/profile.html', args, context_instance=RequestContext(request))

def pin_generator(size=10, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

def send_msg(to_number, text):
    client = TwilioRestClient(TWILIO_ACCOUNT_SID,
                              TWILIO_AUTH_TOKEN)
 
    message = client.messages.create(to=to_number, from_=TWILIO_NUMBER,
                                     body=text)


@login_required
def get_pin(request):
    if request.method == 'POST':
        get_pin_form = GetPinForm(user=request.user, data=request.POST)
        if get_pin_form.is_valid():
            pin = pin_generator()
            phone_number = get_pin_form.cleaned_data['phone_number']
            send_msg(phone_number,pin)
            request.session['pin'] = pin
            request.session['phone_number'] = phone_number
            return HttpResponseRedirect('/profile/verifypin')
    else:
        get_pin_form = GetPinForm(user=request.user)

    args = {}
    args['get_pin_form'] = get_pin_form
    return render_to_response('userprofile/get_pin.html', args, context_instance=RequestContext(request))


@login_required
def verify_pin(request):
    verify_pin_form = VerifyPinForm(request.POST or None)
    if verify_pin_form.is_valid():
        pin = request.session['pin']
        if pin == verify_pin_form.cleaned_data['pin']:
            user = request.user
            profile = user.profile

            phone_number = request.session['phone_number']
            new_verified_phone_number = ProfilePhoneNumber(user_profile=profile,phone_number=phone_number)
            new_verified_phone_number.save()

            profile.phone_number_verified = True
            profile.save()

            teams = Team.objects.filter(phone_number=phone_number)
            for team in teams:
                profile.game_instances.add(team.gameinstance)
                profile.save()
            return HttpResponseRedirect('/profile')
        else:
            return HttpResponseRedirect('/profile/verifypin')
    args = {}
    args['verify_pin_form'] = verify_pin_form
    return render_to_response('userprofile/verify_pin.html', args, context_instance=RequestContext(request))


def _get_pin(length=5):
    """ Return a numeric PIN with length digits """
    return random.sample(range(10**(length-1), 10**length), 1)[0]


def _verify_pin(phone_number, pin):
    """ Verify a PIN is correct """
    return pin == cache.get(phone_number)

@csrf_protect
def ajax_send_pin(request):
    """ Sends SMS PIN to the specified number """
    phone_number = request.POST.get('phone_number', "")
    if not phone_number:
        return HttpResponse("No mobile number", mimetype='text/plain', status=403)

    pin = _get_pin()

    # store the PIN in the cache for later verification.
    cache.set(phone_number, pin, 24*3600) # valid for 24 hrs

    client = TwilioRestClient(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
    message = client.messages.create(
                        body="%s" % pin,
                        to=phone_number,
                        from_=TWILIO_NUMBER,
                    )
    return HttpResponse("Message %s sent" % message.sid, mimetype='text/plain', status=200)



def process_order(request):
    """ Process orders made via web form and verified by SMS PIN. """
    form = OrderForm(request.POST or None)

    if form.is_valid():
        pin = int(request.POST.get("pin", "0"))
        phone_number = request.POST.get("phone_number", "")

        if _verify_pin(phone_number, pin):
            form.save()
            return redirect('transaction_complete')
        else:
            messages.error(request, "Invalid PIN!")
    else:
        return render(
                    request,
                    'order.html',
                    {
                        'form': form
                    }
                )

userprofile/templates/userprofile/get_pin.html
{% extends "default_base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

 <script src="{% static "/dist/js/custom_jquery.js" %}"></script>

{% block jumbotron %}
<div class="row">
  <div class="col-md-12">
    <div class="well well-sm">
    	<h1>Verify your number</h1>
    	<p>By verifying your number we can provide you with a list of your completed quests. It will also speed up your registration for future quests.</p>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="col-ms-12">
    <form method="post" action="">
      {% csrf_token %}
      {% bootstrap_form get_pin_form %}
      {% buttons %}
        <button type="text" class="btn btn-primary" id="search" name="search">
          {% bootstrap_icon "glyphicon glyphicon-share" %} Send me a confirmation PIN
        </button>
      {% endbuttons %}
    </form>
  </div>
</div>
{% endblock %}

userprofile/templates/userprofile/getpin.html
<div class="modal hide" id="contactModal">
<form class="well" method="post" action="/contact/edit/{{ item.id }}">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Editing Contact</h3>
  </div>
  <div class="modal-body">
       {% csrf_token %}
       {{form.as_p}}
  </div>
  <div class="modal-footer">
       <input class="btn btn-primary" type="submit" value="Save" />
       <input name="cancel" class="btn" type="submit" value="Cancel"/>
  </div>
</form>
</div>

userprofile/templates/userprofile/numbers_div.html
{% load bootstrap3 %}
{% load dajaxice_templatetags %}

<div id="verified_numbers">
{% if verified_number_list %}
  <h3>Your Numbers</h3>
    {% for number in verified_number_list %}
      <p><button class="btn btn-danger" data-toggle="modal" onClick="are_you_sure('{{number}}');">{% bootstrap_icon "trash" %}</button>   {{ number }}</p>
    {% endfor %}
  <button class="btn btn-warning" data-toggle="modal" data-target="#myModal">
    Verify Another Number
  </button>
{% else %}
  <button class="btn btn-warning" data-toggle="modal" data-target="#myModal">
    Verify a Number
  </button>
{% endif %} 

  <div class="modal fade" id="confirm_del_modal" tabindex="-1" role="dialog" aria-labelledby="confirm_del_modal_label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" onclick="clear_fields();" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="confirm_del_modal_label">Are you sure?</h4>
        </div>
        <div class="modal-body">
      </div>
    </div>
  </div>

</div>

userprofile/templates/userprofile/profile.html
{% extends "default_base.html" %}

{% load bootstrap3 %}
{% load dajaxice_templatetags %}
{% load static %}

{% block head %}
{% dajaxice_js_import %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="{% static "dist/js/jquery.dajax.core.js" %}" type="text/javascript" charset="UTF-8">></script>

<script>
$(document).ready(function(){
  $("#myModal").load(function(event){ 
    event.preventDefault();
    $("#pin_form_div").hide();  
    $("#id_phone_number").focus();
  });

  $('.ConfirmDelete').click(function() {
      var question = $(this).attr('title');
      if (question == '') question = 'Delete this record?';
      return confirm(question);
  });
});

function stopRKey(evt) { 
  var evt = (evt) ? evt : ((event) ? event : null); 
  var node = (evt.target) ? evt.target : ((evt.srcElement) ? evt.srcElement : null); 
  if ((evt.keyCode == 13) && (node.type=="text"))  {return false;} 
} 

document.onkeypress = stopRKey; 

function go_to_verify(){
    $("#phone_number_form_div").hide();
    $(".help-bock").text("");
    $("#pin_form_div").show();
}

function go_to_get_pin(){
    $("#pin_form_div").hide();
    $(".help-bock").text("");
    $("#phone_number_form_div").show();
}

function send_phone_form(){
    $(".help-block").css('color', 'red');
    Dajaxice.userprofile.phone_form(Dajax.process,{'get_pin_form':$('#phone_number_form').serialize(true)});    
    $("#id_pin").focus();
}

function send_pin_form(){
    Dajaxice.userprofile.verify_form(Dajax.process,{'verify_pin_form':$('#pin_number_form').serialize(true)});
    $("#pin_form_div").hide();
    $(".help-bock").text("");
    $("#phone_number_form_div").show();
    $("#phone_number_form").trigger("reset");
    $("#pin_form").trigger("reset");
}

function clear_fields(){
    $("#phone_number_form").trigger("reset");
    $("#pin_form").trigger("reset"); 
    $("#id_phone_number").focus();
}

function are_you_sure(number){
    Dajaxice.userprofile.delete_number(Dajax.process,{'number':number});
}

jQuery(document).ready(function($) {
});

</script>
{% endblock %}

{% block jumbotron %}
<div class="row">
  <div class="col-md-12">
    <div class="well well-sm">
    	<h1>{{ username }}'s Profile</h1>
    	<p>Here you can view and modify your profile as well as view your quest history</p>
    </div>
  </div>
</div>
{% endblock %}


completed_list.append(game)
in_progress_list.append(game)

{% block content %}
<div class="container">
  <div class="col-md-6">
    {% if in_progress_list or completed_list %}
      {% if in_progress_list %}
        <h1>Quests In Progress</h1>
        {% for game_instance in in_progress_list %}
          <h2>{{ game_instance.competition }}</h2>
          {% if game_instance.started %}
            <h3>Started on {{ game_instance.date_started|date }}</h3>
            <p>You are currently participating in this quest! What are you waiting for, get to it!</p>
          {% else %}
            <h3>Registered on {{ game_instance.date_created|date }}</h3>
            <p>You have registered but have not begun this quest. Please follow the instructions within the sms message you received upon registration, if you have lost this message please refer to your registration confirmation email for further instructions. If all else fails, please contact support at support@point2poiintquests.com</p>
          {% endif %}
          <a class="btn btn-warning" href="{% url 'leaderboard_detail' game_instance.competition.id game_instance.competition.slug %}" role="button">View the leaderboard for {{ game_instance.competition }}</a>
        {% endfor %}
      {% endif %}
      {% if completed_list %}    
        <h1>Completed Quests</h1>
        {% for game_instance in completed_list %}
          <h2>{{ game_instance.competition }}</h2>
          <h3>Started on {{ game_instance.date_started|date }}</h3>
          <a class="btn btn-warning" href="{% url 'leaderboard_detail' game_instance.competition.id game_instance.competition.slug %}" role="button">View the leaderboard for {{ game_instance.competition }}</a>
        {% endfor %}
      {% endif %}
    {% else %}
      <h1>You haven't completed any quests yet!</h1>
      <p>Your completed quests will show up here once you finish them, we promise!</p>
    {% endif %}
    </div>

    <div class="col-md-6">
      <h1>Your Info</h1>
      <h2>Verified Numbers</h2>
      <p>Verifying a phone number lets us display your previous quests on your profile page. We promise that we will only ever
          contact you using your verified numbers with your permission and we will most certainly not sell your information.</p>
      {% include "userprofile/numbers_div.html" %}

      <h2>Other things</h2> 
      <a class="btn btn-warning" href="/accounts/password/change/" role="button">Change Your Password</a>   
      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" onclick="clear_fields();" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="myModalLabel">Verify a Number</h4>
            </div>
            <div class="modal-body">
              <div class="well" id="phone_number_form_div">
                <form method="post" action="" id="phone_number_form" onsubmit="send_phone_form();">
                  {% csrf_token %}
                  {% bootstrap_form get_pin_form %}
                </form>  
                <button id="send_pin_button" class="btn btn-warning" value="Send a confirmation pin" onclick="send_phone_form();">Send a confirmation pin</button>
              </div>
              <div class="well" id="pin_form_div">
                <form method="post" action="" id="pin_number_form" onsubmit="send_pin_form();">
                  {% csrf_token %}
                  {% bootstrap_form verify_pin_form %}
                </form>
                <button id="verify_pin_button" class="btn btn-warning" value="verify pin" onclick="send_pin_form();" data-dismiss="modal">Verify Pin</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

userprofile/templates/userprofile/verify_pin.html
{% extends "default_base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

 <script src="{% static "/dist/js/custom_jquery.js" %}"></script>

{% block jumbotron %}
<div class="row">
  <div class="col-md-12">
    <div class="well well-sm">
    	<h1>Verify your number</h1>
    	<p>By verifying your number we can provide you with a list of your completed quests. It will also speed up your registration for future quests.</p>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}

<div class="container">
  <div class="col-ms-12">
    <form method="post" action="">
      {% csrf_token %}
      {% bootstrap_form verify_pin_form %}
      {% buttons %}
        <button type="submit" class="btn btn-primary" value="verify pin">
          {% bootstrap_icon "glyphicon glyphicon-share" %} Verify Pin 
        </button>
      {% endbuttons %}
    </form>
  </div>
</div>
{% endblock %}